#!/usr/bin/env bash

ssh ubuntu@104.196.50.234 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPnRFgPzvcz8i9cyylSfxlFaaoaEYNrRZwPsrwydX3x1tFgYf4uPf/l3clxka1lBs8gTBHO+Ujgo89D/Gx0gm5WLATqlqaVXEf 9NQWBrdvbU5bnoIqLp9e3K7+RVhsbbg51B9UN7WMfEefSn/DZqqu/cpoRSJ7qHrDHVTvxbJchKj3lh1ubhn9lZD3/U2e7PNs6DQfFhmOnV/85538CHZLtOZBC+nVB06IyBP0nwUX Qgvg7TJO7bo+doWJT+yvQpDxLCiT6luDEJIkRCfq/ewudG3VHtKYDKRbpgP8RHdrVNvJ/7m7SO65uLZ8854ApVtf2ukZH/asHMaWfTsL1Gp5dFS9211f3goGm2xP1LDBtLTHoUYb mCNBo3ggdAyKEBc00KkvfcOfdgTaEITeQ0FJYPD6DGlQQ+pn4nrbibdmhJSbyDaiUT61uK0UcL9yQN8nH77ZwhPlEIOXWw9uTr3Q7yOVp7WJhL73ZhCehXPNZawGuhmsKtiCH0C7 tACPQO0= root@26b543e2b0d6 >> ~ /.ssh/authorized_keys
